extend = "ruff-base.toml"

# These are files to exclude for this project.
extend-exclude = [
  # "**/*.ipynb",  # commonly not ruff-compliant
]

# These are rules that commonly cause many ruff warnings. Code will be improved by
# incrementally fixing code to adhere to these rules, but for practical purposes they
# can be ignored by uncommenting each one. You can also add to this list as needed.
lint.extend-ignore = [
  # "B905", # `zip()` without an explicit `strict=` parameter
  # "PLC1901", # compare-to-empty-string
  # "PLR0911", # Too many returns
  # "PLR0912", # Too many branches
  # "PLR0915", # Too many statements
  # "PGH004", # Use specific rule codes when using `noqa`
  # "C401", # Unnecessary generator (rewrite as a `set` comprehension)
  # "C402", # Unnecessary generator (rewrite as a dict comprehension)
  # "C405", # Unnecessary `list` literal (rewrite as a `set` literal)
  # "C408", # Unnecessary `dict` call (rewrite as a literal)
  # "C416", # Unnecessary `dict` comprehension (rewrite using `dict()`)
  # "G010", # warn is deprecated in favor of warning
  # "PYI056", # Calling `.append()` on `__all__` may not be supported by all type checkers
]
